FROM node:18

# Install gpsbabel
RUN apt-get update && \
    apt-get install -y gpsbabel && \
    apt-get clean

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

ARG DROPBOX_SIGNATURE
ARG DROPBOX_ACCESS_TOKEN
ARG GPS_BABEL_FUNCTIONS_API_BASE_URL
ARG GEOLIB_FUNCTIONS_AP_BASE_URL
ARG GEOFUNCTIONS_FUNCTIONS_AP_BASE_URL
ARG GRAPHCMS_ASSET_BASE_URL
ARG GRAPHCMS_API_URL
ARG GRAPHCMS_API_TOKEN
ARG GRAPHCMS_CDN_URL
ARG GRAPHCMS_CDN_TOKEN
ARG LOCATION_SERVICE_ACCESS_TOKEN
ARG MAPBOX_API_ACCESS_TOKEN
ARG MONGO_DB_URL
ARG MONGO_DB_NAME
ARG STRAVA_VERIFY_TOKEN
ARG STRAVA_CLIENT_ID
ARG STRAVA_CLIENT_SECRET
ARG STRAVA_REFRESH_TOKEN
ARG STRAVA_OWNER_ID
ARG STRAVA_SUBSCRIPTION_ID
ARG ALGOLIA_APPLICATION_ID
ARG ALGOLIA_ADMIN_API_KEY
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG CLOUDINARY_URL
ARG GARMIN_CONNECT_USERNAME
ARG GARMIN_CONNECT_PASSWORD

ENV DROPBOX_SIGNATURE=${DROPBOX_SIGNATURE}
ENV DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
ENV GPS_BABEL_FUNCTIONS_API_BASE_URL=${GPS_BABEL_FUNCTIONS_API_BASE_URL}
ENV GEOLIB_FUNCTIONS_AP_BASE_URL=${GEOLIB_FUNCTIONS_AP_BASE_URL}
ENV GEOFUNCTIONS_FUNCTIONS_AP_BASE_URL=${GEOFUNCTIONS_FUNCTIONS_AP_BASE_URL}
ENV GRAPHCMS_ASSET_BASE_URL=${GRAPHCMS_ASSET_BASE_URL}
ENV GRAPHCMS_API_URL=${GRAPHCMS_API_URL}
ENV GRAPHCMS_API_TOKEN=${GRAPHCMS_API_TOKEN}
ENV GRAPHCMS_CDN_URL=${GRAPHCMS_CDN_URL}
ENV GRAPHCMS_CDN_TOKEN=${GRAPHCMS_CDN_TOKEN}
ENV LOCATION_SERVICE_ACCESS_TOKEN=${LOCATION_SERVICE_ACCESS_TOKEN}
ENV MAPBOX_API_ACCESS_TOKEN=${MAPBOX_API_ACCESS_TOKEN}
ENV MONGO_DB_URL=${MONGO_DB_URL}
ENV MONGO_DB_NAME=${MONGO_DB_NAME}
ENV STRAVA_VERIFY_TOKEN=${STRAVA_VERIFY_TOKEN}
ENV STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
ENV STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
ENV STRAVA_REFRESH_TOKEN=${STRAVA_REFRESH_TOKEN}
ENV STRAVA_OWNER_ID=${STRAVA_OWNER_ID}
ENV STRAVA_SUBSCRIPTION_ID=${STRAVA_SUBSCRIPTION_ID}
ENV ALGOLIA_APPLICATION_ID=${ALGOLIA_APPLICATION_ID}
ENV ALGOLIA_ADMIN_API_KEY=${ALGOLIA_ADMIN_API_KEY}
ENV CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV CLOUDINARY_URL=${CLOUDINARY_URL}
ENV GARMIN_CONNECT_USERNAME=${GARMIN_CONNECT_USERNAME}}
ENV GARMIN_CONNECT_PASSWORD=${GARMIN_CONNECT_PASSWORD}}

# Build the Next.js app
RUN npm run build

# Start the Next.js app
CMD ["npm", "start"]

# Expose port 3000
EXPOSE 3000
